### PR TITLE
Add onDropdown & automaticallyScrollIntoView

### PR DESCRIPTION
**Pull request by bradennapier**
I am thinking you may not want to merge this pull request but I made it to outline the issue I reported.  This should fix the issue by adding onDropdown and automaticallyScrollIntoView props which will do:

`onToggle(onDropdown(isOpened, ref.Select))`

and the other which will just automatically scrolll the dropdown itno view using one of the two options... on webkit it tries scrollIntoViewIfNeeded otherwise a simple scrollIntoview

In addition, when you have timeouts its probably a good idea to have a safetynet.  added timeouts object in Select which makes sure to clearTimeout() when unmounted if any timeouts still exist.

### CODE REVIEW

**Comment by halt-hammerzeit** [comment]
Good point regarding the timeouts and unmounting the component.
I don't know how you implemented that but I guess I'll implement some timeout clearing too.
Also I'm closing this PR due to containing no code changes – you sent compiled JS files diffs which are meaningless.

**Comment by bradennapier** [comment]
What?  It has changes?


https://github.com/Dash-OS/react-phone-number-input/blob/9620fa18e76b8b3bff60d5c280978aeb0334a0a4/source/input.js

**Comment by bradennapier** [comment]
then the timeout handlers:

https://github.com/Dash-OS/react-phone-number-input/blob/f646a7e0d8954b95982c3f76258716b8ac73f67e/source/input.js

**Comment by bradennapier** [comment]
It had the compiled code because i had to add it to the repo so i could install it directly from the git repo and use it

**Pull request closed without merging**
